Task02(script): Fix bugs and refactor code

diff --git a/task02/number-generator b/task02/number-generator
--- a/task02/number-generator
+++ b/task02/number-generator
@@ -8,15 +8,34 @@ random_number=0
 is_guessed=0
 
 get_user_number(){
-  local un
+  local un=""
   read -rp "Enter your number: " un
-  # Check. Is upper_range_limit variable a type of integer ?
-  until [[ $upper_range_limit =~ ^[0-9]+$ ]]; do
+  # Check. Is user_number variable a type of integer ?
+  until [[ -n "$un" ]] || [[ $un =~ ^[0-9]+$ ]]; do
       read -rp "error: \"$un\"cannot be type of int. Try again: " un
   done
   user_number=$un
 }
 
+get_random_number(){
+	random_number=$((RANDOM % upper_range_limit))
+	echo "Generated random number in range [0-$upper_range_limit]"
+}
+
+
+compare(){
+if (( is_guessed == 0 )); then
+  if ((random_number > user_number)); then
+	    echo "Randomly generated number is greater than $user_number"; return 1
+    elif ((random_number < user_number)); then
+	    echo "Randomly generated number is less than $user_number"; return 1
+    else
+      is_guessed=1
+	    echo " Bingo !!! Randomly generated number is $random_number"; return 0
+  fi
+else return 0
+fi;
+}
 
 # Extracting flags from positional parameters
 options=$(getopt -l "upper:,retries:" -o "u:r:" -- "$@")
@@ -52,6 +71,9 @@ until [[ $guessing_tries =~ ^[0-9]+$ ]] && ((guessing_tries >= 1 && guessing_tri
   fi
 done
 
+
+get_random_number
+
 # Getting user_number
 if [[ $# -ge 1 ]] && [[ $1 =~ ^[0-9]+$ ]]; then
   user_number=$1
@@ -59,45 +81,42 @@ if [[ $# -ge 1 ]] && [[ $1 =~ ^[0-9]+$ ]]; then
   else get_user_number
 fi
 
+echo ""
+echo "You have tries: $guessing_tries"
+echo "Your current try: 1"
+compare;
 
-get_random_number(){
-	random_number=$((RANDOM % upper_range_limit))
-	echo "Generated random number in range [0-$upper_range_limit]"
-}
+repeat="-";
+while true; do
 
+  if [ -z "$repeat" ]; then
+      counter=1; get_random_number
+      else counter=2
+  fi
 
-compare(){
-if [ $random_number -gt "$user_number" ]; then
-	echo "randomly generated number is greater than $user_number"
-elif [ $random_number -lt "$user_number" ]; then
-	echo "randomly generated number is less than $user_number"
-else
-  is_guessed=1
-	echo " Bingo !!! Randomly generated number is $random_number"
-fi
-}
-
-get_random_number
-compare
-
-repeat="1";
-while [ "$repeat" == "1" ]; do
-
-
-  counter=1
   # Main loop
-  while [ $counter -lt "$guessing_tries" ]; do
-    if [ $is_guessed = 1 ]; then
-      break
-    fi
-    get_user_number
-    compare
+  until [[ $counter -gt $guessing_tries ]] || (( is_guessed == 1 )); do
+
+    echo ""
+    echo "You have tries: $guessing_tries"
+    echo "Your current try: $counter"
     ((counter++))
+
+    get_user_number
+    if compare; then break; fi
   done
 
-  if [ "$is_guessed" == "1" ]; then
-    read -rp "Play again? - Print \"1\": " repeat
-    counter=1
-    is_guessed=0
+  if (( is_guessed == 1 )); then
+    echo "";read -rp "Play again? (Y/n): " repeat; echo "";
+    if [[ -z "$repeat" ]] || [[ "$repeat" =~ ^[1Yy][e][s] ]]; then
+      repeat=""
+      is_guessed=0
+    else break
+    fi
+  else
+    echo "";
+    echo " ## Ups. Failed. Random number was $random_number";
+    echo "";
+    break
   fi
 done
